name             'simple-web'
#maintainer       'YOUR_COMPANY_NAME'
maintainer       'chef'
#maintainer_email 'YOUR_EMAIL'
maintainer_email 'admin@chef.io'
license          'all_rights'
description      'Installs/Configures simple-web'
long_description 'Installs/Configures simple-web'
version          '0.2.17'

depends 'apt'
depends 'httpd'
